export default {
	CA_VSAV1: "CA VSAV 1",
	COND_VSAV1: "COND VSAV 1",
	EQ_VSAV1: "EQ VSAV 1",

	CA_VSAV2: "CA VSAV 2",
	COND_VSAV2: "COND VSAV 2",
	EQ_VSAV2: "EQ VSAV 2",

	CA_FPTL: "CA FPTL",
	COND_FPTL: "COND FPTL",
	CE1_FPTL: "CE BAT",
	CE2_FPTL: "CE BAL",
	EQ1_FPTL: "EQ BAT",
	EQ2_FPTL: "EQ BAL",

	VLI: "VLI",
	EPA: "EPA",

	SECU: "CADRE SECU",
	CA_FPT: "CA FPT",

	CA_VTU: "CA VTU",
	COND_VTU: "COND VTU",
	EQ_VTU: "EQ VTU",

	CA_VSR: "CA VSR",
	COND_VSR: "COND VSR",
	EQ_VSR: "EQ VSR",

	PHARMACIE: "PHARMACIE",
	REMISE: "REMISE",
	CUISINE: "CUISINE",


}
